### ISSUE TITLE
multiple citation in single record

### ISSUE THREAD

**Issue by jhpoelen** [millerse/Ecological-Database-of-the-World-s-Insect-Pathogens#1]
On line 1067 in interactions.tsv, I noticed a ";" separated list of references (see below). Was this intended? GloBI currently assumes that is a single reference, so the doi resolver gets a bit confused. Suggest to split out each interactions line by line. Alternatively, we can things about ways to support lists in a single citation field.

```1067 EOL:562582  Hypena scabra Larva   RO:0002557  hasPathogen EOL:11926999  Va      irimorpha necatrix    GEONAMES:6252001  USA         Henry, J. E., 1981. Na      tural and applied control of insects by protozoa. Ann. Rev. Entomol. 26: 4      9-73.; Fuxa, J.R., and Brooks, W.M., 1979. Effects of Vairimorpha necatrix       in sprays and corn meal on Heliothis species in tobacco, soybeans, and so      rghum. Journal of Economic Entomology 72: 462-467.; Maddox, J. V.; Brooks,       W. M.; and Fuxa, J. R. Vairimorpha necatrix a pathogen of agricultural pe      sts: potential for pest control. Chapter 31 [pp. 587-594] In, H.D. Burges       (ed.) Microbial Control of Pests and Plant Diseases, 1970-1980. London: Ac      ademic Press, 1981. 949 pp.; Brooks, W. M. 1988. Entomogenous protozoa, pp      . 1-121 in C. M. Ignoffo (ed.) CRC Handbook of Natural Pesticides Vol. 5 M      icrobial Insecticides, Part A, Entomogenous Protozoa and Fungi. CRC Press,       Boca Raton, FL.```

**Comment by millerse** [comment]
Yes.  I discussed this with Katja and Jen and we decided that since the record is reported as having multiple sources we should report the multiple citations as one.  If that makes sense.  If there is a way to support this in a single citation that would be great.

**Comment by jhpoelen** [comment]
list of references are currently treated as one big reference (see http://www.globalbioticinteractions.org/references.html?accordingTo=Vairimorpha%20necatrix%20a%20pathogen%20of%20agricultural&interactionType=interactsWith and attached screenshot). If this is consistent with your desired outcome, please feel free to close this issue.

![screenshot from 2017-05-30 10-19-29](https://cloud.githubusercontent.com/assets/1084872/26595827/850c6172-4521-11e7-9f43-750c4ff4a8a5.png)
