### ISSUE TITLE
Bibio ferruginatus not found in GloBI, but reportedly mentioned in Nematode associations file

### ISSUE THREAD

**Issue by jhpoelen** [millerse/Ecological-Database-of-the-World-s-Insect-Pathogens#3]
see https://github.com/jhpoelen/eol-globi-data/issues/298 .

**Comment by millerse** [comment]
So for some reason, Globi is registering Bibio ferruginatus as just Bibio.  See this: http://www.globalbioticinteractions.org/?accordingTo=Bovien%2C%20P.&interactionType=interactsWith

No idea how this happened because I added the EOL link to the Bibio ferruginatus.

**Comment by jhpoelen** [comment]
@millerse Thanks for looking into this. And yes, the record in the repository does contain an EOL id for  _Bibio ferruginatus_ http://eol.org/pages/756665 . After looking into the GloBI taxonMap, I noticed that the species did get registered to its genus Bibio. Root cause is probably an outage at the time the species was attempted to be resolved that resulted in an attempt to resolve by genus. 

I've removed the entry in the taxon map, and the species should be registered properly in a couple of days.

**Comment by jhpoelen** [comment]
Confirmed that the recent version of taxon graph v0.3.33 contains the expected name mapping:

```
$ echo -e "EOL:756665\tBibio ferruginatus" | nomer append
using default matcher [globi-taxon-cache]
EOL:756665	Bibio ferruginatus	SAME_AS	EOL:756665	Bibio ferruginatus	species		Animalia | Arthropoda | Insecta | Diptera | Bibionidae | Bibio | Bibio ferruginatus	EOL:1 | EOL:164 | EOL:344 | EOL:421 | EOL:500 | EOL_V2:54763 | EOL:756665	kingdom | phylum | class | order | family | genus | species	http://eol.org/pages/756665	
EOL:756665	Bibio ferruginatus	SAME_AS	GBIF:1590934	Bibio ferruginatus	species		Animalia | Arthropoda | Insecta | Diptera | Bibionidae | Bibio | Bibio ferruginatus	GBIF:1 | GBIF:54 | GBIF:216 | GBIF:811 | GBIF:7281 | GBIF:1543369 | GBIF:1590934	kingdom | phylum | class | order | family | genus | species	http://eol.org/pages/756665	
EOL:756665	Bibio ferruginatus	SAME_AS	WD:Q2900973	Bibio ferruginatus	species		| Bibio ferruginatus	WD:Q2029468 | WD:Q2900973	| species	https://www.wikidata.org/wiki/Q2900973	
```

@millerse apologies for the 4 years of delay in confirming the fix on my end.
